[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[start]
command = "uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1"

[healthcheck]
path = "/"
interval = 30
hours = 0
timeout = 10
